version: "3"

networks:
  backend:

services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  welltory_api:
    restart: unless-stopped
    build: .
    container_name: welltory_api
    networks:
      - backend
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    env_file:
      - .env