version: "3"

networks:
  backend:

services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  welltory_api:
    restart: unless-stopped
    build: .
    container_name: welltory_api
    networks:
      - backend
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      - redis
      - celery
    env_file:
      - .env
    volumes:
      - .:/WelltoryTestCase

  celery:
    image: celery:latest
    build:
      context: .
    restart: always
    depends_on:
      - redis
    command: celery -A WelltoryService worker -l info
    networks:
      - backend
    env_file:
      - .env