# Generated by Django 4.0.1 on 2022-01-20 13:54
import random

from django.db import migrations

from faker import Faker
from faker.providers import internet, person, misc


def fake_users(apps, scheme_editor):
    fake = Faker()
    fake.add_provider(internet)
    fake.add_provider(person)
    fake.add_provider(misc)

    WelltoryUser = apps.get_model("service_api", "WelltoryUser")

    for _ in range(100):
        username = fake.user_name()
        first_name = fake.first_name()
        last_name = fake.last_name()
        email = fake.ascii_email()
        weight = round(random.uniform(30.0, 150.0), 2)

        WelltoryUser.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password='123456',
            email=email,
            weight=weight
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fake_users)
    ]
