# Generated by Django 4.0.1 on 2022-01-26 16:29

import random

from django.db import migrations

from faker import Faker
from faker.providers import internet, person, misc


def fake_users(apps, scheme_editor):
    fake = Faker()
    fake.add_provider(internet)
    fake.add_provider(person)
    fake.add_provider(misc)

    User = apps.get_model("auth", "User")

    for _ in range(100):
        username = fake.user_name()
        first_name = fake.first_name()
        last_name = fake.last_name()
        email = fake.ascii_email()

        User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password='123456',
            email=email,
        )


def fake_units(apps, scheme_editor):
    WeightUnit = apps.get_model("service_api", "WeightUnit")
    WeightUnit.objects.create(unit="lb")
    WeightUnit.objects.create(unit="kg")


def fake_weights(apps, scheme_editor):
    Weight = apps.get_model("service_api", "Weight")
    User = apps.get_model("auth", "User")
    WeightUnit = apps.get_model("service_api", "WeightUnit")

    for user_instance in User.objects.all():
        weight = round(random.uniform(30.0, 150.0), 2)
        unit = WeightUnit.objects.get(unit="kg")

        Weight.objects.create(
            weight=weight,
            user=user_instance,
            unit=unit,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fake_users),
        migrations.RunPython(fake_units),
        migrations.RunPython(fake_weights)
    ]
